### ISSUE TITLE
Fails to parse URLs where query string parameters don't have a value

### ISSUE THREAD

**Issue by josip** [palominolabs/url-builder#5]
A URL like `http://test.org?cachebuster` would throw an exception:

```
W/System.err﹕ java.lang.IllegalArgumentException: Malformed query param: <cachebuster>
W/System.err﹕ at com.palominolabs.http.url.UrlBuilder.buildFromQuery(UrlBuilder.java:304)
W/System.err﹕ at com.palominolabs.http.url.UrlBuilder.fromUrl(UrlBuilder.java:145)
W/System.err﹕ at com.palominolabs.http.url.UrlBuilder.fromUrl(UrlBuilder.java:111)
```

Which is not correct as the URL is valid, since query parameters don't necessarily have to have a "value".

**Comment by marshallpierce** [comment]
Good catch. Do you think it's important to be able to build a query param that has no equals sign? Right now you can create something with an empty value, but it will still put the =.

**Comment by marshallpierce** [comment]
I think actually to be compliant with the spec (http://www.w3.org/TR/html401/interact/forms.html#form-content-type and the various RFCs), the best I can do is expose a monolithic "query" which is the entire query string, and also (if possible) decompose it into query param `key=value` pairs. I'll see what I can do in terms of representing this in an API that isn't confusing.

**Comment by marshallpierce** [comment]
What do you think of the approach I've implemented in https://github.com/palominolabs/url-builder/compare/feature/unstructured-query?diff=unified&name=feature%2Funstructured-query? Would this solve your use case? In effect, it makes it so that you can either have a UrlBuilder that has one query that it doesn't try to further parse, or it will break it down into query param pairs. Another approach would be to introduce the concept of a degenerate pair that has no value part, but that wouldn't handle the case of `?q=1=1` for instance.

**Comment by marshallpierce** [comment]
v1.1.1 has been released and fixes this issue.
