### ISSUE TITLE
Inconsistencies in handling slash ( / ) character.

### ISSUE THREAD

**Issue by AlexTrotsenko** [palominolabs/url-builder#9]
The **same** url, when constructed by different `UrlBuilde` methods, results in **different** url when `UrlBuilde.toUrlString()` is called:
 When value, which is passed to `.pathSegments()` is a *relative url* with slashes, then those slashes are translated to `%2F` and can't be properly parsed on the server-side.

See example:

````.Java


	@Override
	protected void onCreate(Bundle savedInstanceState) {
        String fullURl = "http://10.121.9.36:59840/dbdev/_design/agenda/_view/main-timetable";

        final String httpScheme = "http";
        final String host = "10.121.9.36";
        final int port = 59840;

        final String relativeUrl = "dbdev/_design/agenda/_view/main-timetable";
        final String[] relativeUrlParts = relativeUrl.split("/");

        try {
            UrlBuilder builderFullUrl = UrlBuilder.fromUrl(new URL(fullURl));
            Log.v("UrlBuilder", "builderFullUrl: " + builderFullUrl.toUrlString());

            UrlBuilder builderRelativeUrl = UrlBuilder.forHost(httpScheme, host, port);
            builderRelativeUrl.pathSegment(relativeUrl);
            Log.v("UrlBuilder", "builderRelativeUrl: " + builderRelativeUrl.toUrlString());

            UrlBuilder builderRelativeUrlParts = UrlBuilder.forHost(httpScheme, host, port);
            builderRelativeUrlParts.pathSegments(relativeUrlParts);
            Log.v("UrlBuilder", "builderRelativeUrlParts: " + builderRelativeUrlParts.toUrlString());
        } catch (CharacterCodingException | MalformedURLException e) {
            e.printStackTrace();
        }
	}
````

Output:
```
V/UrlBuilder: builderFullUrl:          http://10.121.9.36:59840/dbdev/_design/agenda/_view/main-timetable
V/UrlBuilder: builderRelativeUrl:      http://10.121.9.36:59840/dbdev%2F_design%2Fagenda%2F_view%2Fmain-timetable
V/UrlBuilder: builderRelativeUrlParts: http://10.121.9.36:59840/dbdev/_design/agenda/_view/main-timetable
```

**Comment by marshallpierce** [comment]
This is correct behavior. If you say you want a path segment that has a `/` in it, then the `/` must be encoded (as `%2F`) because `/` is the path segment delimiter. That's why when you provide a string that already has / in it to `pathSegment()` you get `%2F`.

By writing your relativeUrl string by hand that contains the complete path, you're kinda going against the whole point of this library, which is to let the library assemble things with the correct delimiters for you. I suggest calling `pathSegments("dbdev", "_design", ...)`. This is guaranteed to be safe and correct and should produce the URL you want.

**Comment by AlexTrotsenko** [comment]
I assumed, that this might be according to design, but it worth to create an issue and check with someone much more aware than me.

@marshallpierce thanks for your explanations about the logic of the library.

**Comment by marshallpierce** [comment]
Thanks for asking. I hope the library helps you make the best URLs around. :)
